"""company_signals

Revision ID: 231699b88165
Revises: 205bc8f9adc4
Create Date: 2026-07-01 19:49:43.499394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231699b88165'
down_revision: Union[str, Sequence[str], None] = '205bc8f9adc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_signals',
    sa.Column('company_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('accounts_overdue', sa.Boolean(), nullable=False),
    sa.Column('accounts_next_due', sa.Date(), nullable=True),
    sa.Column('confirmation_overdue', sa.Boolean(), nullable=False),
    sa.Column('has_insolvency', sa.Boolean(), nullable=False),
    sa.Column('has_charges', sa.Boolean(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_signals')
    # ### end Alembic commands ###
