"""initial schema

Revision ID: 2810f1148005
Revises: 
Create Date: 2026-06-27 18:19:54.863624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2810f1148005'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('runway_weeks', sa.Integer(), nullable=False),
    sa.Column('has_shortfall', sa.Boolean(), nullable=False),
    sa.Column('minimum_reserve', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_business_id'), 'analysis_runs', ['business_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_created_at'), 'analysis_runs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_runs_created_at'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_business_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('businesses')
    # ### end Alembic commands ###
